### ISSUE TITLE
What is 2.097.152? 

### ISSUE THREAD

**Issue by aurelian17** [horia-delicoti/kernel-module#3]
Please replace the 2.097.152 with some define that clarifies what this number represents.

**Comment by horia-delicoti** [comment]
The number is now replaced with a define buffer_size. 
ID: dc16d1624fa21cfd21dc15e3f96e02b3ec01a8d9

**Comment by aurelian17** [comment]
where? because the commit id indicated cannot be found on github on development branch.

**Comment by horia-delicoti** [comment]
Replaced with a proper define. 
ID: 037023f067dfa31b821c3944d4f45636ef9cf312

**Comment by aurelian17** [comment]
Ok, looks better now.
